/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EliteIndexRouteImport } from './routes/elite.index'
import { Route as EliteSlugRouteImport } from './routes/elite.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteIndexRoute = EliteIndexRouteImport.update({
  id: '/elite/',
  path: '/elite/',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteSlugRoute = EliteSlugRouteImport.update({
  id: '/elite/$slug',
  path: '/elite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elite/$slug': typeof EliteSlugRoute
  '/elite/': typeof EliteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elite/$slug': typeof EliteSlugRoute
  '/elite': typeof EliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elite/$slug': typeof EliteSlugRoute
  '/elite/': typeof EliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elite/$slug' | '/elite/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elite/$slug' | '/elite'
  id: '__root__' | '/' | '/elite/$slug' | '/elite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EliteSlugRoute: typeof EliteSlugRoute
  EliteIndexRoute: typeof EliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/': {
      id: '/elite/'
      path: '/elite'
      fullPath: '/elite/'
      preLoaderRoute: typeof EliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/$slug': {
      id: '/elite/$slug'
      path: '/elite/$slug'
      fullPath: '/elite/$slug'
      preLoaderRoute: typeof EliteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EliteSlugRoute: EliteSlugRoute,
  EliteIndexRoute: EliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
